controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

nelmio_api_doc_json:
    path: /api/docs.json
    controller: nelmio_api_doc.controller.swagger

nelmio_api_doc:
    path: /api/docs
    controller: nelmio_api_doc.controller.swagger_ui