version: '3.8'

services:
  backend:
    build: ./backend/symfony
    container_name: symfony_backend
    working_dir: /var/www/html
    volumes:
      - ./backend/symfony:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/fixourcity"
    command: php -S 0.0.0.0:8000 -t public

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fixourcity
    volumes:
      - ./Docker/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "support@fixourcity.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev

volumes:
  pgdata: