@echo off
echo Uruchamianie Dockera...
docker compose -f docker\docker-compose.yml up -d

echo Backend...
start "Backend" cmd /k "cd backend && php -S 127.0.0.1:8000 -t public"

echo Worker Messengera...
start "Worker" cmd /k "cd backend && php bin/console messenger:consume async -vv"

echo Frontend...
start "Frontend" cmd /k "cd frontend && npm install && npm run dev"
