gesdinet_jwt_refresh_token:
    ttl: 900
    user_identity_field: email
    firewall: api
    token_parameter_name: refresh_token
    single_use: true
    refresh_token_class: App\Entity\RefreshToken
