lexik_jwt_authentication:
    secret_key:       '%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key:       '%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        3600  # 1h access token

    token_extractors:
        authorization_header:
            enabled: false
        cookie:
            enabled: true
            name: ACCESS_TOKEN

    set_cookies:
        access_token_cookie:
            name:       'ACCESS_TOKEN'
            lifetime:   3600
            path:       '/'
            secure:     true
            httpOnly:   true
            samesite:  'lax'
