security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        register:
            pattern: ^/api/register
            stateless: true
            provider: app_user_provider

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider

        token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            provider: app_user_provider

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/register,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,               roles: IS_AUTHENTICATED_FULLY }
