security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        register:
            pattern: ^/api/v1/auth/register$
            security: false

        refresh:
            pattern: ^/api/v1/auth/token/refresh$
            security: false

        login:
            pattern: ^/api/v1/auth/login$
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/v1/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/v1
            stateless: true
            lazy: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/v1/auth/register$,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/auth/login$,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/auth/token/refresh$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1,                     roles: IS_AUTHENTICATED_FULLY }
